# Generated by Django 5.0 on 2023-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog1_Details_conent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heading', models.TextField()),
                ('blog_Detail_Img', models.ImageField(upload_to='Blog Detail Img')),
            ],
        ),
        migrations.CreateModel(
            name='Blog1_Details_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog2_Details_conent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heading', models.TextField()),
                ('blog2_Detail_Img', models.ImageField(upload_to='Blog Detail2 Img')),
            ],
        ),
        migrations.CreateModel(
            name='Blog2_Details_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog3_Details_conent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('blog3_Detail_Img', models.ImageField(upload_to='Blog Detail3 Img')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('blogImg', models.ImageField(upload_to='Blog Images')),
            ],
        ),
        migrations.CreateModel(
            name='Latest_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('latest_img', models.ImageField(upload_to='Latest Post Images')),
            ],
        ),
    ]
